### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by doggy8088** [nii236/k#1]
Here is the error message:

```
$ go get -u github.com/golang/dep/cmd/dep
$ go get github.com/nii236/k
can't load package: package github.com/nii236/k: no Go files in /home/will/go/src/github.com/nii236/k
```

GO version:

```
$ go version
go version go1.9.2 linux/amd64
```

**Comment by nii236** [comment]
Hi @doggy8088, thanks for your issue!

I've updated the readme with new installation instructions.  Basically you needed to add `/...` to the end of the `go get command`.

I've also made a release with pre-compiled binaries. You can download the releases [here](https://github.com/nii236/kk/releases/tag/0.0.1). This will make it easier to install.

I hope that helps!

**Comment by doggy8088** [comment]
@nii236 What's the "..." mean?  What can I replace "..." with something? or I have to put "..." exactly in the command?  Sorry, I never write golang but I do use k8s.

**Comment by doggy8088** [comment]
@nii236 I finally installed, but still failed. Two problems.

1. after `go install cmd/kk/main.go` will install `main` in GOBIN.  it should be `kk`.

2. When I run kk, I got the following error:
![image](https://user-images.githubusercontent.com/88981/34583614-5ef58fd6-f1d3-11e7-8235-7e0bfade1f2d.png)

**Comment by nii236** [comment]
Hi @doggy8088, did you remember to `git pull` the latest version? Have you tried running the binary directly from the release that I uploaded?

What is your distro? I will start a VM and try to replicate your issue.

**Comment by doggy8088** [comment]
@nii236 Yes, I pulled the latest version.  I also tried the binary version, the error is the same.

Your README use `main` too.
![image](https://user-images.githubusercontent.com/88981/34597299-d3b69462-f220-11e7-864d-f099461dd953.png)

My distro & version below:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

BTW, What's the "..." mean?

**Comment by nii236** [comment]
Hey @doggy8088, the "..." refers to all subdirectories (recursive).

In this case, the `main` package is located in `github.com/nii236/kk/cmd/kk/`. This is why you need `go get github.com/nii236/kk/...`, as it will then fetch and install the relevant files in the `cmd` subfolder.

I will try to spin up the app in an ubuntu container and will get back to you.

**Comment by nii236** [comment]
Hi @doggy8088, I managed to spin up on a fresh Ubuntu docker install without any issues.

I've updated the readme with the install instructions and correct binary names.

Please try to install again with `go install ./...` instead of the previous `go install cmd/kk/main.go`.

Can you please give me the output of:

- `kk`
- `DEBUG=true kk`
- `kk --help`

**Comment by doggy8088** [comment]
```
will@WILL10LENOVO2:~$ kk
invalid argument
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf6cac8]

goroutine 1 [running]:
github.com/nii236/kk/pkg/ui.(*App).Run(0x0, 0x0, 0x0)
        /home/will/go/src/github.com/nii236/kk/pkg/ui/ui.go:38 +0x38
main.run(0xc4204fe160, 0xc4204fe160, 0xc4204a9ad7)
        /home/will/go/src/github.com/nii236/kk/cmd/kk/main.go:47 +0x34d
github.com/nii236/kk/vendor/github.com/urfave/cli.HandleAction(0x102c0c0, 0x121cd20, 0xc4204fe160, 0xc4203501e0, 0x0)
        /home/will/go/src/github.com/nii236/kk/vendor/github.com/urfave/cli/app.go:490 +0xd2
github.com/nii236/kk/vendor/github.com/urfave/cli.(*App).Run(0xc4203324e0, 0xc4200101a0, 0x1, 0x1, 0x0, 0x0)
        /home/will/go/src/github.com/nii236/kk/vendor/github.com/urfave/cli/app.go:264 +0x635
main.main()
        /home/will/go/src/github.com/nii236/kk/cmd/kk/main.go:104 +0x7f4
will@WILL10LENOVO2:~$ DEBUG=true kk
INFO[0000] Running in DEBUG mode
invalid argument
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf6cac8]

goroutine 1 [running]:
github.com/nii236/kk/pkg/ui.(*App).Run(0x0, 0x0, 0x0)
        /home/will/go/src/github.com/nii236/kk/pkg/ui/ui.go:38 +0x38
main.run(0xc42032d080, 0xc42032d080, 0xc4200a1ad7)
        /home/will/go/src/github.com/nii236/kk/cmd/kk/main.go:47 +0x34d
github.com/nii236/kk/vendor/github.com/urfave/cli.HandleAction(0x102c0c0, 0x121cd20, 0xc42032d080, 0xc4201401e0, 0x0)
        /home/will/go/src/github.com/nii236/kk/vendor/github.com/urfave/cli/app.go:490 +0xd2
github.com/nii236/kk/vendor/github.com/urfave/cli.(*App).Run(0xc420332680, 0xc4200101a0, 0x1, 0x1, 0x0, 0x0)
        /home/will/go/src/github.com/nii236/kk/vendor/github.com/urfave/cli/app.go:264 +0x635
main.main()
        /home/will/go/src/github.com/nii236/kk/cmd/kk/main.go:104 +0x7f4
will@WILL10LENOVO2:~$ kk --help
NAME:
   k - Terminal User Interface (TUI) for Kubernetes

USAGE:
   kk [global options] command [command options] [arguments...]

VERSION:
   0.0.1

DESCRIPTION:
   For when you are sick of typing namespaces over and over again

COMMANDS:
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --kubeconfig-path value, -c value  Kubeconfig path (Uses $HOME) (default: "/home/will/.kube/admin.conf") [$KUBECONFIG_PATH]
   --refresh-interval value           Seconds between updates (default: 1) [$REFRESH_INTERVAL]
   --auto-refresh, -a                 Automatic refresh [$AUTO_REFRESH]
   --production, -p                   Production mode [$PRODUCTION]
   --debug, -d                        Debug logging [$DEBUG]
   --log-to-file, -f                  Log to file [$LOG_TO_FILE]
   --log-file-path value              File to log to (default: "/tmp/debug.log") [$LOG_FILE_PATH]
   --test, -t                         Use the K8S mock client [$TEST]
   --help, -h                         show help
   --version, -v                      print the version
```

**Comment by nii236** [comment]
Hi @doggy8088, unfortunately I can not reproduce the bug so I can not help you at this time. 

I started a fresh ubuntu docker container and managed to get the app running successfully.

I will have to close the issue for now until you can provide a reliable way for me to reproduce the bug.

Sorry!

**Comment by doggy8088** [comment]
@nii236 I was using WSL in my Windows 10 1709 that run Ubuntu 16.04.3.  Do you have any Windows 10 box to reproduce this problem?

**Comment by nii236** [comment]
Hi @doggy8088, WSL is not supported at this time. The WSL environment is not the same as running Ubuntu directly and I do not have the hardware to test it.
